import { format, addDays, subDays } from 'date-fns'

const today = format(new Date(), 'yyyy-MM-dd')
const yesterday = format(subDays(new Date(), 1), 'yyyy-MM-dd')
const tomorrow = format(addDays(new Date(), 1), 'yyyy-MM-dd')
const dayAfter = format(addDays(new Date(), 2), 'yyyy-MM-dd')
const nextWeek = format(addDays(new Date(), 7), 'yyyy-MM-dd')

export const mockSettings = {
  candidate_name: 'João da Silva',
  logo_url: null,
  primary_color: '#1a3a6b',
  secondary_color: '#c9a84c',
  slogan: 'Por um futuro melhor para todos',
}

export const mockTeam = [
  {
    id: 'user-1',
    name: 'João da Silva',
    email: 'joao@agenda.com',
    phone: '92991234567',
    role: 'Candidato',
    access_level: 'admin',
    avatar_url: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Maria Santos',
    email: 'maria@agenda.com',
    phone: '92992345678',
    role: 'Coordenadora de Campanha',
    access_level: 'coordenador',
    avatar_url: null,
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Carlos Oliveira',
    email: 'carlos@agenda.com',
    phone: '92993456789',
    role: 'Assessor de Imprensa',
    access_level: 'coordenador',
    avatar_url: null,
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Ana Lima',
    email: 'ana@agenda.com',
    phone: '92994567890',
    role: 'Voluntária',
    access_level: 'visualizador',
    avatar_url: null,
    created_at: '2024-01-04T00:00:00Z',
  },
]

export const mockAppointments = [
  {
    id: 'apt-1',
    title: 'Reunião com lideranças do bairro Compensa',
    date: today,
    start_time: '08:00',
    end_time: '09:30',
    location: 'Centro Comunitário Compensa',
    address: 'Rua das Flores, 120',
    city: 'Manaus',
    neighborhood: 'Compensa',
    responsible_id: 'user-1',
    type: 'reuniao',
    priority: 'alta',
    status: 'confirmado',
    observations: 'Levar material de apresentação sobre o projeto de pavimentação',
    map_link: '',
    involved_people: ['Maria Santos', 'Carlos Oliveira'],
    result: '',
    next_step: 'Enviar proposta formal até sexta-feira',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${yesterday}T10:00:00Z`,
    updated_at: `${yesterday}T10:00:00Z`,
  },
  {
    id: 'apt-2',
    title: 'Visita à Comunidade Santo Antônio',
    date: today,
    start_time: '10:00',
    end_time: '12:00',
    location: 'Comunidade Santo Antônio',
    address: 'AM-010, Km 15',
    city: 'Manaus',
    neighborhood: 'Santo Antônio',
    responsible_id: 'user-1',
    type: 'visita',
    priority: 'alta',
    status: 'confirmado',
    observations: 'Visita de campo para levantamento de demandas de infraestrutura',
    map_link: '',
    involved_people: ['Ana Lima'],
    result: '',
    next_step: 'Registrar demandas coletadas',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${yesterday}T11:00:00Z`,
    updated_at: `${yesterday}T11:00:00Z`,
  },
  {
    id: 'apt-3',
    title: 'Entrevista Rádio AM 980',
    date: today,
    start_time: '14:00',
    end_time: '15:00',
    location: 'Estúdio Rádio AM 980',
    address: 'Av. Eduardo Ribeiro, 500',
    city: 'Manaus',
    neighborhood: 'Centro',
    responsible_id: 'user-1',
    type: 'entrevista',
    priority: 'alta',
    status: 'confirmado',
    observations: 'Pauta: projetos para saúde e educação. Levar dados do plano de governo.',
    map_link: '',
    involved_people: ['Carlos Oliveira'],
    result: '',
    next_step: '',
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: `${yesterday}T14:00:00Z`,
    updated_at: `${yesterday}T14:00:00Z`,
  },
  {
    id: 'apt-4',
    title: 'Evento Público - Praça da Democracia',
    date: today,
    start_time: '17:00',
    end_time: '20:00',
    location: 'Praça da Democracia',
    address: 'Av. Getúlio Vargas, s/n',
    city: 'Manaus',
    neighborhood: 'Chapada',
    responsible_id: 'user-2',
    type: 'evento_publico',
    priority: 'alta',
    status: 'confirmado',
    observations: 'Show cultural + discurso. Esperado público de 500 pessoas.',
    map_link: '',
    involved_people: ['Maria Santos', 'Carlos Oliveira', 'Ana Lima'],
    result: '',
    next_step: 'Divulgar nas redes sociais',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${yesterday}T16:00:00Z`,
    updated_at: `${yesterday}T16:00:00Z`,
  },
  {
    id: 'apt-5',
    title: 'Reunião de alinhamento da equipe',
    date: tomorrow,
    start_time: '07:30',
    end_time: '08:30',
    location: 'Comitê Central',
    address: 'Rua Recife, 1500',
    city: 'Manaus',
    neighborhood: 'Adrianópolis',
    responsible_id: 'user-2',
    type: 'agenda_interna',
    priority: 'media',
    status: 'confirmado',
    observations: 'Revisar agenda da semana e distribuição de tarefas',
    map_link: '',
    involved_people: ['Maria Santos', 'Carlos Oliveira', 'Ana Lima'],
    result: '',
    next_step: '',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${today}T08:00:00Z`,
    updated_at: `${today}T08:00:00Z`,
  },
  {
    id: 'apt-6',
    title: 'Caminhada no Bairro São Jorge',
    date: tomorrow,
    start_time: '09:00',
    end_time: '12:00',
    location: 'Bairro São Jorge',
    address: 'Concentração na Igreja Matriz',
    city: 'Manaus',
    neighborhood: 'São Jorge',
    responsible_id: 'user-1',
    type: 'caminhada',
    priority: 'alta',
    status: 'confirmado',
    observations: 'Caminhada popular com distribuição de material',
    map_link: '',
    involved_people: ['Maria Santos', 'Ana Lima'],
    result: '',
    next_step: '',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${today}T09:00:00Z`,
    updated_at: `${today}T09:00:00Z`,
  },
  {
    id: 'apt-7',
    title: 'Gravação de vídeo institucional',
    date: dayAfter,
    start_time: '14:00',
    end_time: '17:00',
    location: 'Estúdio Produtora Visual',
    address: 'Av. Djalma Batista, 2000',
    city: 'Manaus',
    neighborhood: 'Chapada',
    responsible_id: 'user-3',
    type: 'gravacao',
    priority: 'media',
    status: 'pendente',
    observations: 'Vídeo sobre propostas para a área rural',
    map_link: '',
    involved_people: ['Carlos Oliveira'],
    result: '',
    next_step: 'Confirmar com a produtora',
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: `${today}T10:00:00Z`,
    updated_at: `${today}T10:00:00Z`,
  },
  {
    id: 'apt-8',
    title: 'Visita à Escola Municipal Paulo Freire',
    date: nextWeek,
    start_time: '10:00',
    end_time: '11:30',
    location: 'Escola Municipal Paulo Freire',
    address: 'Rua dos Tucunarés, 200',
    city: 'Manaus',
    neighborhood: 'Cidade Nova',
    responsible_id: 'user-1',
    type: 'visita',
    priority: 'media',
    status: 'pendente',
    observations: 'Reunião com diretora para tratar de reformas estruturais',
    map_link: '',
    involved_people: [],
    result: '',
    next_step: 'Confirmar data com a secretaria',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${today}T11:00:00Z`,
    updated_at: `${today}T11:00:00Z`,
  },
  {
    id: 'apt-9',
    title: 'Reunião com Secretaria de Saúde',
    date: yesterday,
    start_time: '09:00',
    end_time: '10:30',
    location: 'Secretaria Municipal de Saúde',
    address: 'Av. André Araújo, 701',
    city: 'Manaus',
    neighborhood: 'Aleixo',
    responsible_id: 'user-1',
    type: 'reuniao',
    priority: 'alta',
    status: 'concluido',
    observations: 'Tratou de propostas para ampliação de UBS',
    map_link: '',
    involved_people: ['Maria Santos'],
    result: 'Secretaria se comprometeu a enviar relatório de demandas por bairro',
    next_step: 'Aguardar relatório até próxima semana',
    created_by: 'user-2',
    updated_by: 'user-1',
    created_at: `${yesterday}T07:00:00Z`,
    updated_at: `${today}T08:00:00Z`,
  },
]

export const mockDemands = [
  {
    id: 'dem-1',
    person_name: 'Antônia Ferreira',
    phone: '92991234567',
    city: 'Manaus',
    neighborhood: 'Compensa',
    type: 'saude',
    description: 'Solicita medicamento controlado para filha com epilepsia. UBS não tem estoque há 3 meses.',
    responsible_id: 'user-2',
    status: 'em_andamento',
    priority: 'alta',
    expected_return_date: tomorrow,
    observations: 'Família em situação vulnerável. Criança de 8 anos.',
    next_step: 'Acionar Secretaria de Saúde',
    result: '',
    appointment_id: 'apt-1',
    tags: ['#saúde', '#urgente', '#criança'],
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: `${today}T09:30:00Z`,
    updated_at: `${today}T09:30:00Z`,
  },
  {
    id: 'dem-2',
    person_name: 'Associação de Moradores do Santo Antônio',
    phone: '92992345678',
    city: 'Manaus',
    neighborhood: 'Santo Antônio',
    type: 'infraestrutura',
    description: 'Ramal com 2km sem pavimentação. Famílias ficam ilhadas no período de chuvas.',
    responsible_id: 'user-1',
    status: 'nova',
    priority: 'alta',
    expected_return_date: nextWeek,
    observations: 'Afeta aproximadamente 300 famílias',
    next_step: 'Levantar custo de pavimentação',
    result: '',
    appointment_id: 'apt-2',
    tags: ['#ramal', '#infraestrutura', '#urgente'],
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: `${today}T11:00:00Z`,
    updated_at: `${today}T11:00:00Z`,
  },
  {
    id: 'dem-3',
    person_name: 'Pedro Rodrigues',
    phone: '92993456789',
    city: 'Manaus',
    neighborhood: 'Compensa',
    type: 'educacao',
    description: 'Escola sem telhado no bloco B. Aulas suspensas quando chove.',
    responsible_id: 'user-2',
    status: 'em_analise',
    priority: 'alta',
    expected_return_date: dayAfter,
    observations: 'Escola Estadual Dom Pedro II',
    next_step: 'Contatar Secretaria de Educação',
    result: '',
    appointment_id: 'apt-1',
    tags: ['#educação', '#infraestrutura'],
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: `${yesterday}T14:00:00Z`,
    updated_at: `${today}T10:00:00Z`,
  },
  {
    id: 'dem-4',
    person_name: 'Liderança Comunitária - Dona Rosa',
    phone: '92994567890',
    city: 'Manaus',
    neighborhood: 'Cidade Nova',
    type: 'regularizacao_fundiaria',
    description: 'Comunidade de 150 famílias sem documentação fundiária. Área ocupada há 20 anos.',
    responsible_id: 'user-1',
    status: 'aguardando_retorno',
    priority: 'media',
    expected_return_date: nextWeek,
    observations: 'Processo já iniciado no ITERAM, aguardando análise',
    next_step: 'Acompanhar processo no ITERAM',
    result: '',
    appointment_id: null,
    tags: ['#regularização', '#liderança'],
    created_by: 'user-2',
    updated_by: 'user-1',
    created_at: `${yesterday}T16:00:00Z`,
    updated_at: `${today}T09:00:00Z`,
  },
  {
    id: 'dem-5',
    person_name: 'Francisco Sousa',
    phone: '92995678901',
    city: 'Manaus',
    neighborhood: 'São Jorge',
    type: 'emprego_renda',
    description: 'Jovem de 22 anos buscando oportunidade de qualificação profissional. Técnico em informática incompleto.',
    responsible_id: 'user-3',
    status: 'em_andamento',
    priority: 'baixa',
    expected_return_date: nextWeek,
    observations: 'Encaminhar para programa de qualificação do SINE',
    next_step: 'Contato com SINE Manaus',
    result: '',
    appointment_id: null,
    tags: ['#emprego', '#educação'],
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: `${yesterday}T10:00:00Z`,
    updated_at: `${yesterday}T10:00:00Z`,
  },
  {
    id: 'dem-6',
    person_name: 'Comunidade Novo Horizonte',
    phone: '92996789012',
    city: 'Manaus',
    neighborhood: 'Novo Horizonte',
    type: 'ramal',
    description: 'Falta de energia elétrica em 80 residências. Comunidade atendida por gerador há 5 anos.',
    responsible_id: 'user-2',
    status: 'resolvida',
    priority: 'alta',
    expected_return_date: yesterday,
    observations: 'Demanda encaminhada para Amazonas Energia',
    next_step: '',
    result: 'Amazonas Energia confirmou instalação da rede para o próximo mês',
    appointment_id: null,
    tags: ['#energia', '#urgente'],
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: `${yesterday}T08:00:00Z`,
    updated_at: `${today}T07:00:00Z`,
  },
]

export const mockDemandHistory = {
  'dem-1': [
    { id: 'h1', action: 'Criação', description: 'Demanda cadastrada durante reunião no Compensa', user_id: 'user-1', created_at: `${today}T09:30:00Z` },
    { id: 'h2', action: 'Atualização de status', description: 'Status alterado para "Em Andamento". Contato feito com Secretaria de Saúde.', user_id: 'user-2', created_at: `${today}T11:00:00Z` },
  ],
  'dem-3': [
    { id: 'h3', action: 'Criação', description: 'Demanda registrada após relato de moradores', user_id: 'user-2', created_at: `${yesterday}T14:00:00Z` },
    { id: 'h4', action: 'Atualização', description: 'Enviado ofício para Secretaria de Educação. Protocolo: 2024-1234', user_id: 'user-2', created_at: `${today}T10:00:00Z` },
  ],
  'dem-6': [
    { id: 'h5', action: 'Criação', description: 'Demanda urgente de energia registrada', user_id: 'user-1', created_at: `${yesterday}T08:00:00Z` },
    { id: 'h6', action: 'Encaminhamento', description: 'Contato com superintendente da Amazonas Energia realizado', user_id: 'user-2', created_at: `${yesterday}T15:00:00Z` },
    { id: 'h7', action: 'Resolução', description: 'Confirmado prazo de instalação. Demanda encerrada com sucesso!', user_id: 'user-2', created_at: `${today}T07:00:00Z` },
  ],
}

export const mockNotes = [
  {
    id: 'note-1',
    title: 'Ponto de atenção — Reunião Compensa',
    content: 'Lideranças do Compensa demonstraram insatisfação com a demora no atendimento das demandas de saúde. É necessário dar retorno rápido para não perder apoio neste bairro. Aproximadamente 2.000 votos em jogo.',
    date: today,
    type: 'atencao',
    created_by: 'user-1',
    created_at: `${today}T10:00:00Z`,
  },
  {
    id: 'note-2',
    title: 'Pessoas importantes — Visita Santo Antônio',
    content: 'Sr. Raimundo Pinto (presidente da associação) — 92997654321. Muito influente na área. Prometeu mobilizar lideranças para o evento de quinta-feira. Tratar com atenção especial.',
    date: today,
    type: 'pessoa',
    created_by: 'user-2',
    created_at: `${today}T12:00:00Z`,
  },
  {
    id: 'note-3',
    title: 'Relato do dia — Reunião Secretaria Saúde',
    content: 'Reunião muito produtiva. Secretário receptivo às propostas. Foco nas UBS do Compensa e São Jorge. Prometeu dados até próxima semana. Clima positivo para cooperação.',
    date: yesterday,
    type: 'relato',
    created_by: 'user-1',
    created_at: `${yesterday}T11:00:00Z`,
  },
]

export const mockCurrentUser = {
  id: 'user-1',
  name: 'João da Silva',
  email: 'joao@agenda.com',
  access_level: 'admin',
  role: 'Candidato',
}
